name: Build and Deploy ASP.NET MVC (.NET Framework)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      run: nuget restore FuneralSupport.sln

    - name: Build with MSBuild
      run: msbuild FuneralSupport.sln /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DeployTarget=Package

    - name: Publish to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fotinopoulos'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ github.workspace }}/FuneralSupport/obj/Release/Package/FuneralSupport.zip
